### ISSUE TITLE
Add Sentry Release job to CI

### ISSUE THREAD

**Issue by dr-rompecabezas** [dr-rompecabezas/qugenai-archived#13]
Add to `.github/workflows/ci.yml`.

```yaml
      - uses: actions/checkout@v4
      - name: Sentry Release
        uses: getsentry/action-release@v1.7.0
        env:
          SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
          SENTRY_ORG: ${{ secrets.SENTRY_ORG }}
          SENTRY_PROJECT: ${{ secrets.SENTRY_PROJECT }}
        with:
          environment: production
```
